//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomeDialogBox.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SomeDialogBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [中止]と[再試行]と[無視] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AbortRetryIgnore {
            get {
                return ResourceManager.GetString("AbortRetryIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   円で囲まれた小文字の i から成る記号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Asterisk {
            get {
                return ResourceManager.GetString("Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefButton1 {
            get {
                return ResourceManager.GetString("DefButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefButton2 {
            get {
                return ResourceManager.GetString("DefButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefButton3 {
            get {
                return ResourceManager.GetString("DefButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスクラメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exclamation {
            get {
                return ResourceManager.GetString("Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景が赤の円で囲まれた白い X から成る記号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [OK] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [OK]と[キャンセル] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OKCancel {
            get {
                return ResourceManager.GetString("OKCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [再試行]と[キャンセル] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RetryCancel {
            get {
                return ResourceManager.GetString("RetryCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [はい]と[いいえ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [はい]と[いいえ]と「キャンセル」 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesNoCancel {
            get {
                return ResourceManager.GetString("YesNoCancel", resourceCulture);
            }
        }
    }
}
